version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - .:/coreservices
    depends_on:
      - db
    environment:
      - FLASK_APP=core.py
    command: flask run
    networks:
      - housesappnetwork

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python -u consumer.py"
    depends_on:
      - db
      - backend
    networks:
      - housesappnetwork

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: core
      MYSQL_USER: microservice
      MYSQL_PASSWORD: microservice
      MYSQL_ROOT_PASSWORD: microservice
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "$$MYSQL_USER",
          "--password=$$MYSQL_PASSWORD",
        ]
    networks:
      - housesappnetwork

volumes:
  dbdata:

networks:
  housesappnetwork:
    external: true
